version: "3.3"
services:
 forms:
  build: .
  expose: ["80"]
  volumes:
    - ./src:/app
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.forms-service.rule=HostRegexp(`forms.{domain:[a-zA-Z0-9-]+}.{tld:[a-zA-Z0-9-]+}`)"
   - "traefik.http.routers.forms-service.entrypoints=websecure"
   - "traefik.http.routers.forms-service.tls.certresolver=myresolver"
# To your webapp's config, add:
#   - "traefik.http.routers.forms-example.rule=Host(`forms.example.com`)"
#   - "traefik.http.routers.forms-example.entrypoints=websecure"
#   - "traefik.http.routers.forms-example.tls.certresolver=myresolver"
#   - "traefik.http.routers.forms-example.service=forms-form-data-service@docker"